### ISSUE TITLE
sign-up error

### ISSUE THREAD

**Issue by adagiomzr** [adagiomzr/wwTniKB1#2]
first submit of "create new user" leads into an error message

"SyntaxError: Unexpected end of JSON input"

**Comment by adagiomzr** [comment]
I think when putting this line in comment "return response.json();" within the signup function the problem is resolved.

can someone check? @bruyninxmaarten @WoutBrugmansPXL

**Comment by bruyninxmaarten** [comment]
It does fix the error, maybe there is no json response so we are parsing an empty string(?) which leads to the unexpected end of json input error
